version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - metricalonetwork
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=metricalo
      - DB_USERNAME=secret
      - DB_PASSWORD=secret

  web:
    image: nginx:alpine
    container_name: web
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - metricalonetwork
    depends_on:
      - app
      - db

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=metricalo
      - MYSQL_USER=secret
      - MYSQL_PASSWORD=secret
    networks:
      - metricalonetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '8090:80'
    depends_on:
      - db
    networks:
      - metricalonetwork

networks:
  metricalonetwork:
    driver: bridge

volumes:
  dbdata:
